/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_trilingua;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zxsyn
 */
public class beranda extends javax.swing.JFrame {

    private HashTable dictionary;

    /**
     * Creates new form beranda
     */
    public beranda(HashTable dictionary) {
        this.dictionary = dictionary;
        initComponents();
        refreshTable();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWord = new javax.swing.JButton();
        searchWord = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKata = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keterangan = new javax.swing.JTextArea();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addWord.setText("Tambah Kata");
        addWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordActionPerformed(evt);
            }
        });
        getContentPane().add(addWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 160, 110, 40));

        searchWord.setText("Search");
        searchWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWordActionPerformed(evt);
            }
        });
        getContentPane().add(searchWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 110, 40));

        tabelKata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Indonesia", "Inggris", "Jawa"
            }
        ));
        jScrollPane2.setViewportView(tabelKata);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 660, 170));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        keterangan.setColumns(20);
        keterangan.setRows(5);
        jScrollPane1.setViewportView(keterangan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 660, 120));

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 420, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/beranda.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWordActionPerformed
        // TODO add your handling code here:
        String key = searchField.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tabelKata.getModel();
        model.setRowCount(0);

        if (key.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan kata yang akan dicari.", "Error", JOptionPane.ERROR_MESSAGE);
            refreshTable();
            return;
        }
        Data result = dictionary.find(key);
        if (result != null) {
            model.setRowCount(0);
            model.addRow(new Object[]{result.getIndonesian(), result.getEnglish(), result.getJawa()});
            keterangan.setText(getKeterangan(result.getKet()));
        } else {
            JOptionPane.showMessageDialog(this, "Kata tidak ditemukan.", "Tidak Ditemukan", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
        }
    }//GEN-LAST:event_searchWordActionPerformed

    private void addWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordActionPerformed
        // TODO add your handling code here:
        new add(dictionary, this).setVisible(true);
    }//GEN-LAST:event_addWordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        HashTable dictionary = new HashTable(200);
        dictionary.insert("Aku", "I", "Kula", "Aku punya ANJING kecil");
        dictionary.insert("Ibu", "Mother", "Mak", "Ibu adalah Istrinya Ayah");
        dictionary.insert("Ayah", "Father", "Bapak", "Ayah adalah Suaminya Ibu");

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beranda(dictionary).setVisible(true);
                new beranda(dictionary).setLocationRelativeTo(null);
            }
        });
    }

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tabelKata.getModel();
        model.setRowCount(0); // Hapus semua baris di tabel
        for (Data data : dictionary.getAllData()) {
            if (data != null) {
                model.addRow(new Object[]{data.getIndonesian(), data.getEnglish(), data.getJawa()});
//                keterangan.setText(getKeterangan(data.getKet()));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea keterangan;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton searchWord;
    private javax.swing.JTable tabelKata;
    // End of variables declaration//GEN-END:variables

    private String getKeterangan(String key) {
        return key;
    }
}
